export const CONSTANTS = {
    DATA_SOURCE: 'DATA_SOURCE',
    USER_REPOSITORY: 'USER_REPOSITORY',
    LINKS_REPOSITORY: 'LINKS_REPOSITORY',
    QR_CODE_REPOSITORY: 'QR_CODE_REPOSITORY',
    INVALIDATE_TOKEN_REPOSITORY: 'INVALIDATE_TOKEN_REPOSITORY',
    IS_PUBLIC_KEY: 'isPublic',
    IS_REDIRECTION_KEY: 'isRedirection'
}

export const {
    DATA_SOURCE,
    USER_REPOSITORY,
    LINKS_REPOSITORY, 
    INVALIDATE_TOKEN_REPOSITORY,
    IS_PUBLIC_KEY, 
    IS_REDIRECTION_KEY,
    QR_CODE_REPOSITORY
} = CONSTANTS